###LST AND SYMPTOMS 
model1 <- glm(fhapp~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)
model1 <- glm(fhh~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)
model1 <- glm(flife~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)
model1 <- glm(fsuic~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)
model1 <- glm(fslp~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)
model1 <- glm(fmove~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)
model1 <- glm(finad~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)
model1 <- glm(ftired~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)
model1 <- glm(fdepre~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)
model1 <- glm(fconc~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)
model1 <- glm(fappe~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)
model1 <- glm(finte~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)
model1 <- glm(fwor~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)
model1 <- glm(frestl~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)
model1 <- glm(frelax~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)
model1 <- glm(fann~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)
model1 <- glm(fworr~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)
model1 <- glm(ffore~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)
model1 <- glm(fnerv~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model1)

###UHII AND SYMPTOMS
model2 <- glm(fhapp~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
model2 <- glm(fhh~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
model2 <- glm(flife~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
model2 <- glm(fsuic~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
model2 <- glm(fslp~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
model2 <- glm(fmove~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
model2 <- glm(finad~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
model2 <- glm(ftired~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
model2 <- glm(fdepre~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
model2 <- glm(fconc~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
model2 <- glm(fappe~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
model2 <- glm(finte~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
model2 <- glm(fwor~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
model2 <- glm(frestl~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
model2 <- glm(frelax~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
model2 <- glm(fann~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
model2 <- glm(fworr~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
model2 <- glm(ffore~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
model2 <- glm(fnerv~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp,family='binomial', dataset)
summary(model2)
