###LST AND WM
model1 <- glm(wm_md_tfma~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_md_tfmi~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_md_tmcp~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_md_tar~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_md_tart~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_md_tcgpc~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_md_tct~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_md_tifof~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_md_tilf~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_md_tml~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_md_tppc~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_md_tptr~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_md_tslf~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_md_tstr~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_md_tuf~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_isovf_tfma~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_isovf_tfmi~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_isovf_tmcp~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_isovf_tar~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_isovf_tart~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_isovf_tcgpc~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_isovf_tct~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_isovf_tifof~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_isovf_tilf~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_isovf_tml~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_isovf_tppc~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_isovf_tptr~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_isovf_tslf~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_isovf_tstr~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)
model1 <- glm(wm_isovf_tuf~blsts+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model1)


###UHI AND WM
model2 <- glm(wm_md_tfma~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_md_tfmi~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_md_tmcp~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_md_tar~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_md_tart~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_md_tcgpc~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_md_tct~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_md_tifof~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_md_tilf~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_md_tml~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_md_tppc~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_md_tptr~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_md_tslf~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_md_tstr~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_md_tuf~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_isovf_tfma~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_isovf_tfmi~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_isovf_tmcp~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_isovf_tar~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_isovf_tart~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_isovf_tcgpc~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_isovf_tct~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_isovf_tifof~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_isovf_tilf~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_isovf_tml~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_isovf_tppc~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_isovf_tptr~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_isovf_tslf~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_isovf_tstr~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
model2 <- glm(wm_isovf_tuf~buhiis+age0+sex+edu+income+ethnic+whr0+nosmoking+drinkingM+sleeph+regular+dieth+htnp+dmp+cadp, family='gaussian', dataset)
summary(model2)
